apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new_service
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - HOSTNAME_PLACEHOLDER
    secretName: TLS_SECRET_NAME_PLACEHOLDER
