source:
  kind: ConfigMap
  name: new_service-environment-values
  fieldPath: data.INGRESS_TLS_SECRET_NAME
targets:
- select:
    kind: Ingress
    name: new_service
  fieldPaths:
    - spec.tls.[secretName=TLS_SECRET_NAME_PLACEHOLDER].secretName
  options:
    create: true