source:
  kind: ConfigMap
  name: new_service-environment-values
  fieldPath: data.HOSTNAME_PLACEHOLDER
targets:
- select:
    kind: Ingress
    name: new_service
  fieldPaths:
    - spec.tls.*.hosts.[=HOSTNAME_PLACEHOLDER]
  options:
    create: true