apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  name: new_service-environment-values
  envs:
  - environment-values.env
- behavior: merge
  name: new_service-container-vars
  envs:
  - .env
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/version: 
namespace: staging
resources:
  - ../../base

components:
  - ../../components/ingress

images:
- name: me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo/new_service
  newTag: 