apiVersion: kustomize.config.k8s.io/v1beta1
labels:
- pairs:
    app: new_service
configMapGenerator:
- name: new_service-environment-values
  envs:
  - environment-values.env
- name: new_service-container-vars
  envs:
  - .env
generatorOptions:
  disableNameSuffixHash: true # use a static name
kind: Kustomization
resources:
- deployment.yaml
- service.yaml